### ISSUE TITLE
CLI: Signing keys

### ISSUE THREAD

**Issue by samlown** [invopop/gobl.cli#3]
This was going to be put inside an RFC, but the reality is that it's pretty short.

The CLI needs to be able to support signing envelopes, otherwise it's not very useful as all gobl documents require at least one signature to be valid. The main complication around this is where and how to store the JSON Web Keys.

There are two main options we've come up with so far:

 * Support loading `~/.gobl/config.yaml` file with a configuration containing private keys (this is what Invocli does)
 * An SSH-style approach whereby private and public keys are stored in a `~/.gobl` directory like `id_es256.jwk` for the private key and optionally `id_es256.pub.jwk` for the public key.

The SSH-like option is perhaps the most interesting as it opens up a set of possible commands on the interface:

 * Implies there is a default key, useful for setting up gobl as a microservice.
 * Adding an ssh-like `-i ~/.gobl/test_es256.jwk` option to specific a new identify file works easily.
 * A `gobl keygen` command can create a key and output it to the `~/.gobl` directory.

GOBL already contains everything required to generate signatures inside the `dsig` package, so this is just a question of creating an interface.

We're expecting users to be able to upload their public keys to Invopop for storage, they should be easy to get to either by looking at the `~/.gobl/id_es256.pub.jwk` file, or by generating it from the private key via the command line.

Key files are always in JSON format. Is it useful to add a `.jwk` or `.json` extension to each?

**Comment by flimzy** [comment]
I think this issue has now been implemented. Are there any details I've overlooked that still need attention, @samlown ?
